language: python
python:
  - "3.6"

addons:
  apt:
    packages:
      # for jupyter notebook rendering
      - pandoc
      # for building latex/pdf
      - texlive-base
      - texlive-generic-recommended
      - texlive-fonts-recommended
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-latex-extra
      - latexmk
      - latex-xcolor
      - dvipng
      - dvidvi

env:
  matrix:
    - TARGET: html
      SPHINXOPTS: -W
    - TARGET: latexpdf

install:
  - pip install --upgrade pip
  - pip install -r docs/requirements.txt

script: 
  - make -C docs pre-docs
  - make -C docs $TARGET
